name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      IS_GITEA: ${{ secrets.IS_GITEA }}
    strategy:
      matrix:
        node-version:
          - latest
        bun-version:
          - latest
    steps:
      - name: checkout page branch
        uses: actions/checkout@v4
      #      - name: Use Node.js ${{ matrix.node-version }}
      #        uses: actions/setup-node@v2
      #        with:
      #          node-version: ${{ matrix.node-version }}
      - name: Use bun-js ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install dependencies
        run: bun i
      - name: Build page
        run: bun run build
      - name: Check platform
        run: |
          if [ "${{ secrets.IS_GITEA }}" = "true" ]; then
            echo "hello gitea"
          else
            echo "GITHUB"
          fi
      - name: configure the page.
        uses: actions/configure-pages@v4
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/notes/.vitepress/dist
      - name: Deploy page
        uses: actions/deploy-pages@v4
